language: ruby
rvm:
  - 2.3.3
env:
  - COVERAGE=true JRUBY_OPTS=--debug
sudo: false
cache: bundler
before_script:
  - git clone --depth 1 https://github.com/errbit/errbit-docs.git /tmp/errbit-docs
  - cd /tmp/errbit-docs && bundle install --binstubs && ERRBIT_PATH=$TRAVIS_BUILD_DIR bundle exec jekyll build && cd $TRAVIS_BUILD_DIR
  # - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-2.6.10.tgz -O /tmp/mongodb.tgz
  # - tar -xvf /tmp/mongodb.tgz
  # - mkdir /tmp/data
  # - ${PWD}/mongodb-linux-x86_64-2.6.10/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --auth &> /dev/null &
  # - bundle exec rake errbit:bootstrap
script:
  - true
  # - bundle exec rspec
  # - bundle exec rubocop --lint
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
